### ISSUE TITLE
Tweaks to About Us page.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#11]
1. Its PV Solar Report, not PV Reports :)
2. Could you please justify all bios instead of center align (below is an example)
   ![image](https://f.cloud.github.com/assets/4460231/547268/2fd527b0-c2bd-11e2-9dab-9a3713c0203f.png)
3. Also, Timo & Barry bios here .. 

"A solar expert, inventor of ‘plug and play’ solar panels, current CEO of Cinnamon Solar, former CEO of Westinghouse Solar."

"A software prodigy, Google engineer, cleantech enthusiast and founder of Nexopia - once Canada's largest social network for young people."

We can fit in advisor bios if we decrease font size of all our names and remove the line break between Founder photo & bio.

**Comment by dhanur** [comment]
btw, the fonts on this page are working perfectly!

**Comment by ghost** [comment]
I compressed as far as I could get it and didn't quite get rid of the scroll bar.  Not going to spend any more time on this because once we add our titles the scroll bar will be needed.
