### ISSUE TITLE
"Sorry no data found page"

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#12]
We get this page for correctly formated but non-existent zip codes (for eg., 94370)
![image](https://f.cloud.github.com/assets/4460231/553469/6d3041de-c386-11e2-975a-5624a64583dd.png)

Can we change this to,
Change Headline to - "Ouch, that doesn't look like a real Zip Code to us."
Delete - "There is no data found for your request"
Change Button Text to - "Let's Try Again?"

This is a quick and easy one, and would be a nice touch cos users are bound to put correctly formatted non-existent zipcodes :)

Thx!

Dhanur

**Comment by ghost** [comment]
This one was easy.  Is the message too long for the headline?

**Comment by dhanur** [comment]
That's ok, I love it!
