### ISSUE TITLE
Let's delete the annoying line on Non-Fresno pages.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#13]
Lots of feedback that this line is not prominent enough, and its tricky to make it bigger because of spacing issues.
"We’re not in your county yet, but we can remind you the second we are!"

So I have a simple solution. Lets just delete that line and rename the button to "Let Me Know When You Launch!"

Simple enough :)

**Comment by ghost** [comment]
Yea, that one is been bugging me for a while.  Done.

**Comment by dhanur** [comment]
Need to change button text.

**Comment by ghost** [comment]
Sorry missed that.  It's a big button.
