### ISSUE TITLE
Add zip and ip to Contact Us / Sign Me Up database records

### ISSUE THREAD

**Issue by ghost** [dhanur/Sunible-Beta#19]
When a user fills out the Contact Us or Sign Me Up forms, capture IP and zipcode in data sent.

**Comment by ghost** [comment]
Contact Us form now captures IP Address and Timestamp and writes values to database.  NOTE:  zip code still not stored - need Roman to adjust his code to pass zip to php function.

**Comment by ghost** [comment]
"Sign me up" form now sends zip and IP data to Salesforce  Timestamp is automatically added when lead is received in Salesforce.  Also, created online way to check Contact Us table.  You need to log into Salesforce to see Sign Me Up lead.

**Comment by suniblestephen** [comment]
Great John
