### ISSUE TITLE
Add Twitter, Facebook and LinkedIn icons to web page

### ISSUE THREAD

**Issue by ghost** [dhanur/Sunible-Beta#20]

**Comment by swenson86** [comment]
Because of the technical requests that Dhanur has for this, I will do my best to implement but may need to defer to Roman for completion.

**Comment by ghost** [comment]
OK, thanks for the heads up.  Let me know how things go.

Give me a call when you can.

Thanks.

John

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
Have discussed on email, but I'm putting the specs for Social Media links below again ..

a. Placement: Icons to be alongside the footer links, not in a corner. See illustration linked below.
b. Icons can be downloded here - http://cl.ly/310y3H1C1N1v
c. Alignment: Needs to be vertical-center-aligned with the footer links, and the whole group (footer links + social icons) need to be horizontal-center-aligned to the page). Here's an illustration - http://grab.by/o7oo
d. Links: www.facebook.com/sunible ,  www.twitter.com/sunible , http://www.linkedin.com/company/sunible

**Comment by rlytvynchuk** [comment]
Icons added. Assigned to QA

**Comment by svlasenko** [comment]
I expected when I click on these buttons it will be open in new tab but not in the same. Is it possible to implement in this way? What do you think about it? Should I create a new enhancement?

**Comment by dhanur** [comment]
Thanks for catching Sveta. No need for separate issue to be logged. Roman, could you please change this to open in new tab?

**Comment by rlytvynchuk** [comment]
implemented. Assigned to QA

**Comment by svlasenko** [comment]
Verified in Master and Trunk
