### ISSUE TITLE
Phone number format

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#23]
We need to allow the first 10 digits to be entered then automatically format it (regardless of what chars are entered).

**Comment by dhanur** [comment]
Yep, I've been meaning to log this. Also, please change the auto format to (XXX) XXX-XXXX, right now there's no space between the 4th & 5th digit like so .. (XXX)XXX-XXXX. Its minor but its killing me :)

**Comment by dhanur** [comment]
Sorry I meant right now there's no space between 3rd and 4th digit.

**Comment by dhanur** [comment]
Nicely done! You underestimate your talents, Mr. CTO.

**Comment by swenson86** [comment]
Good job John!
