### ISSUE TITLE
Blog must open on new page.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#24]
Else user loses progress and will hate us.

**Comment by ghost** [comment]
Blog does open on new page, doesn't it?  Hit the back button.  I set it up
as an <a href>

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
Nope, it opens in same window, and back button takes me back to landing page (i.e. all progress is lost). I cleared cache and checked.

**Comment by ghost** [comment]
OK, it's really the same issue as the back button.  Once that is fixed,
this will be too.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
John, couldn't we simply make the blog link open in a new window using the 'target' 'new window' html attribute? It's a simple fix.
Back button won't be fixed for several weeks.
Thanks,

Dhanur

**Comment by ghost** [comment]
Is that really going to be better?  You have to close the window and some
browsers treat that as a popup and block them.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by suniblestephen** [comment]
I thought it opened in a separate window yesterday? Now it is opening in
the same window, what happened?

-ST

On Wed, Jun 5, 2013 at 2:09 PM, John Bissell notifications@github.comwrote:

> OK, it's really the same issue as the back button. Once that is fixed,
> this will be too.
> 
> John Bissell
> CTO
> 
> Solar Simplified
> 
> Cell: (510) 229-0577
> Skype: john.bissell
> Email: john@sunible.com
> 
> 55 Harrison Street, 3rd Floor
> Oakland, CA 94607
> 
> On Wed, Jun 5, 2013 at 2:06 PM, dhanur notifications@github.com wrote:
> 
> > Nope, it opens in same window, and back button takes me back to landing
> > page (i.e. all progress is lost). I cleared cache and checked.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/solarisbetter/beta/issues/24#issuecomment-19008584>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/24#issuecomment-19008785
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by ghost** [comment]
OK you are right.  It does go to a new tab.  Shows how old I am - last time
I did this browsers didn't have tabs so it always opened a new window.

I pushed the change to the main site.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
:+1: :)
