### ISSUE TITLE
Blog fixed

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#25]
issue with ghost post (Fresno), unique url for each post, ability to add new posts

**Comment by ghost** [comment]
-> blog.sunible.com and sunible.com/blog both work and take user to Sunible blog.
-> ghost post (Fresno) gone.  It was only a picture right?  
-> unique URL problem - FIXED.  Stick with the Post Title as the unique identifier - adding the date to the URL is a problem.  If this won't work then I will need to reconfigure the date format in the URL
-> ability to add new posts - FIXED.

**Comment by swenson86** [comment]
It is currently only working at sunible.com/blog , blog.sunible.com does
not work. I think I can switch this around but only one at a time will work
with full functionality. There isn't any date showing up in the links that
I see just the permalink, based off of the title of the post.

Tanner Swenson
tanner@sunible.com

**Comment by swenson86** [comment]
This also causes another issue, the link from the sunible logo will not go
to the sunible.com home page, we will need to change that in a PHP file I
think.

Tanner Swenson
tanner@sunible.com

**Comment by ghost** [comment]
Now can include date in URL along with post name.  If the Permalink setting is changed, please let me know as I need to make a code change for the sunible.com/blog url to work.

**Comment by swenson86** [comment]
I logged out because someone else was making changes to the permalink
settings. Do we want sunible.com/blog or blog.sunible.com because we can
only really use one. I will need to make two changes if we want
blog.sunible.com.

Tanner Swenson
tanner@sunible.com

**Comment by ghost** [comment]
Tanner,

Should have let you know that I was on it.   I was trying to get the
subdomain blog.sunible.com to navigate.  Just sent an email update on
outcome.  I'm done if you want to use it now.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by ghost** [comment]
CORRECTION:  blog.sunible.com subdomain deactivated.  use sunible.com/blog to access

**Comment by suniblestephen** [comment]
do we need the date in the post?

On Wed, Jun 12, 2013 at 8:38 AM, John Bissell notifications@github.comwrote:

> Now can include date in URL along with post name. If the Permalink setting
> is changed, please let me know as I need to make a code change for the
> sunible.com/blog url to work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/25#issuecomment-19334305
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by swenson86** [comment]
If everything is working then I won't touch the permalink information.
