### ISSUE TITLE
Delete Date in Post Title

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#26]
Tanner, please delete date in Post Title.

![image](https://f.cloud.github.com/assets/4460231/647195/04420a24-d3fb-11e2-8c30-eb2e1a677586.png)

Note for Stephen - lets keep the 'by Sunible' .. this is an author tag. Clicking on it takes the user to a page of all posts made by that author. This is important since we will have guest bloggers.

**Comment by dhanur** [comment]
This has not been resolved.

**Comment by ghost** [comment]
I thought you did it yourself by just selecting a different permalink.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
This issue is not about the Permalink, its about the date under the Post Title (see screenshot attached to bug description)

**Comment by swenson86** [comment]
No testing needed, removed date from blog post using WordPress plugin.
