### ISSUE TITLE
Safari (mac): Leaflet map problem

### ISSUE THREAD

**Issue by ghost** [dhanur/Sunible-Beta#28]
Leaflet maps do not render consistently for Safari browsers on Mac

This issue is related to other UI issues logged already including the wrong font (should be Bariol Regular) showing up on screens (i.e. FAQ) on the Mac.

**Comment by ghost** [comment]
To replicate use:
Safari: Version 6.0.5 (8536.30.1)
Mac: Version 10.8.4
![image1](https://f.cloud.github.com/assets/3856727/712894/6ac4c7d2-deb4-11e2-88ee-af1edba26015.jpg)

**Comment by rlytvynchuk** [comment]
![issue28](https://f.cloud.github.com/assets/1098812/721680/1f254dfa-dfeb-11e2-8890-dab7ba3ef3ea.png)

Here is the screenshot how it looks on my mac. Versions are highlighted with yellow bg

Please specify the ZIP you enter (I used 93210) Maybe it helps

**Comment by ghost** [comment]
Thanks Roman. I have the same map rendering problem, but only in areas outside of Fresno. Can you try using zip 94598. The crazy thing is, once I go in and click on the map or zoom or move the map, it shows fine. So it is only an initial load problem that resolves itself when I do stuff with the map.

**Comment by rlytvynchuk** [comment]
issue closed.

As this item says, the solution is to disable webkit3d before map loads
https://github.com/Leaflet/Leaflet/issues/1435

I disable it only on init and only for Safari. After map is paned transformations are enabled again, so zooming and scrolling isn't affected

**Comment by suniblestephen** [comment]
Hmm, I still get the same problem (attached screenshot) I used zip 94596
for Contra Costa County.

-ST

On Fri, Jun 28, 2013 at 12:08 PM, rlytvynchuk notifications@github.comwrote:

> issue closed.
> 
> As this item says, the solution is to disable webkit3d before map loads
> Leaflet/Leaflet#1435 https://github.com/Leaflet/Leaflet/issues/1435
> 
> I disable it only on init and only for Safari. After map is paned
> transformations are enabled again, so zooming and scrolling isn't affected
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/28#issuecomment-20208066
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by suniblestephen** [comment]
Sorry guys.  I jumped the gun on this one.  Roman is pushing the fix to
GitHub now.  It was just fixed on his local platform.

once in Git, I'll pust to production and ask you guys to test.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```
