### ISSUE TITLE
Remove the underlines

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#3]
and if possible, make the mouse pointer turn to a hand when hovered on a question (I think Tanner/Roman could help you out)

**Comment by ghost** [comment]
I've asked Tanner to take a look at this.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
Tanner, please look into this .. we're ready to go live. It would be a rookie design error to have a text cursor over clickable content.

**Comment by swenson86** [comment]
I have made suggestions about what the solution may be, I didn't know if I was actually supposed to go into the code and make changes myself? Here is a copy of my suggestion -

'Have you tried to change the "a", or hyperlink style to include "text-decoration:none;", this is usually the simplest way to remove the underline from the links. We will have to make sure that it is only for the FAQ section and doesn't affect the whole web app. For the cursor, I think we need to add cursor: pointer; into the CSS as well for the links.'

Inline styling:
'in the HTML link tag add "style=" and the CSS information, there is also an addition called "!important" that will supposedly override any strong CSS code.'

What document is the FAQ HTML in, im assuming the web-app index file? Do I need to edit the one in the beta folder? I just didn't want to be making any changes to the code as I haven't had my fingers in it for a while. Please let me know if I should go forth with attempting to change the style of the underlined links, I will want to make a back up I suppose as I don't want to cause any irreparable changes to the beta.

**Comment by swenson86** [comment]
Hoping that my response on GitHub went to everyone, just letting you know I
replied if it didn't.

Tanner Swenson
tanner@sunible.com

**Comment by ghost** [comment]
Tanner - got your response.  The best way to get familiar with Git and the code base is to start working on it, so why not implement your suggestion?  Be sure to create a branch off the master when you are working on the fix.

**Comment by ghost** [comment]
In addition to the mouse over and underlines, there is a font problem - on some browsers and on the mac the font used is not Bariol - it looks like Times New Roman.  This was in another issue that I closed so am including it here.

**Comment by swenson86** [comment]
Okay, so do I just click on index.html on the Code page, and click edit, and make my changes? Does it automatically back up all code versions?

**Comment by ghost** [comment]
Give me a call

**Comment by dhanur** [comment]
(Changed the issue title)

Tanner, here's a summary of changes we need for the FAQ box .. 
1. Everything on the page (except Headline) in blue
2. Mouseover turns text yellow and turns pointer into hand
3. Fonts need to be Bariol (appearing as Times NR on Macs)
4. Remove underlines on Questions

To see an example, just enter a non-CA zip code and mouseover the survey choices .. that is exactly the effect we need on FAQs.

Did you get a chance to call John and discuss?

**Comment by dhanur** [comment]
Tanner, I see the FAQ thing hasn't been fixed yet (see my last comment for a summary of the changes required) .. could you get this done once you're done with the blog & text transcription?
