### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#31]
Change "Select" text on dashboard page column heading to "Request Quote"

**Comment by ghost** [comment]
DONE

**Comment by suniblestephen** [comment]
Still has the old text on my machine

On Fri, Jun 28, 2013 at 11:58 AM, John Bissell notifications@github.comwrote:

> DONE
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/31#issuecomment-20207516
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com
