### ISSUE TITLE
Data on dashboard

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#32]
AC-Electric shows "null" systems and other installers seem to have wrong totals.

**Comment by ghost** [comment]
Added data load script to have Null values replaced with 0's. - FIXED.

Unclear on what is wrong with totals.  Please provide an example of an installer and the expected total installs for zip code 93710.

**Comment by suniblestephen** [comment]
How can AC have 0 installs and be active, I thought we made the cutoff at
leas one install in the past 6 months. I thought SolarCity had more
installs, I am going to look at the data now.

-ST

On Fri, Jun 28, 2013 at 4:00 PM, John Bissell notifications@github.comwrote:

> Added data load script to have Null values replaced with 0's. - FIXED.
> 
> Unclear on what is wrong with totals. Please provide an example of an
> installer and the expected total installs for zip code 93710.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/32#issuecomment-20219068
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by ghost** [comment]
I am looking at the data now... In Fresno County SolarCity had 1,067, Real Goods 663, Valley Unique 405, REC 454, Arise 274, Verengo 343.

In Sunible right now... In Fresno County SolarCity has 844, Real Goods 578, REC 410, Valley Unique 354, Verengo 269, Arise 254

That's just to give you and example, but they are all off. :)

-ST

**Comment by ghost** [comment]
We're going to need to compare query logic.  The query used in the site is:

SELECT count(*) FROM csi, installer_county
WHERE csi.`Contractor License Number` = installer_county.license_number
AND csi.`Customer County`= installer_county.county
AND csi.`Customer Segment`='Residential'
AND csi.`Installed Status` = 'Installed'
GROUP BY csi.`Contractor License Number`, csi.`Customer County`

The web site totals match the clean csi table.

To validate, I did an ad-hoc query on the clean CSI table that summed up all the residential installed arrays for Fresno county for contractor # 888104 (SolarCity) and the number was 844.

I'll redownload the csv file from last week to dig into this further.

**Comment by ghost** [comment]
Load scripts modified and tested to ensure web site reflects data in latest scrub
