### ISSUE TITLE
Put Sunible Phone Number prominently on site

### ISSUE THREAD

**Issue by ghost** [dhanur/Sunible-Beta#34]
Use 3rd party service like BoldChat or Click2Call.

**Comment by dhanur** [comment]
John, as mentioned in my email to everyone on this subject today .. I will send you a design spec. What we have up there is not ok, don't know why it went up.

From email .. 
"I'm ok if we just want to go with the phone number display for now - I can provide you with a design spec today (yep, even this needs consideration on contrast, placement, visibility and clutter - for all screens!)"

**Comment by swenson86** [comment]
This was my doing, Stephen mentioned that he wanted the phone number up
ASAP, I added it to my changes and sent to GitHub yesterday. It may not
blend perfectly with look and feel at this point but I did match the color
with the blue from the infographics on home page. I don't think it will
cause more harm than good while we implement new design as we need that
resource for people if they will use it. I don't think it is that visually
intrusive or too far off of our design platform as well. Please get me new
design specs asap and I can make changes as soon as possible and send
through to GitHub.

Tanner

Tanner Swenson
tanner@sunible.com

**Comment by suniblestephen** [comment]
Correct, I think we need the number up, as soon as we have the correct
graphic, graphic we can switch them out.

Looking good :)

-ST

On Wed, Jul 3, 2013 at 5:41 PM, Tanner notifications@github.com wrote:

> This was my doing, Stephen mentioned that he wanted the phone number up
> ASAP, I added it to my changes and sent to GitHub yesterday. It may not
> blend perfectly with look and feel at this point but I did match the color
> with the blue from the infographics on home page. I don't think it will
> cause more harm than good while we implement new design as we need that
> resource for people if they will use it. I don't think it is that visually
> intrusive or too far off of our design platform as well. Please get me new
> design specs asap and I can make changes as soon as possible and send
> through to GitHub.
> 
> Tanner
> 
> Tanner Swenson
> tanner@sunible.com
> 
> On Wed, Jul 3, 2013 at 5:37 PM, dhanur notifications@github.com wrote:
> 
> > John, as mentioned in my email to everyone on this subject today .. I
> > will
> > send you a design spec. What we have up there is not ok, don't know why
> > it
> > went up.
> > 
> > From email ..
> > "I'm ok if we just want to go with the phone number display for now - I
> > can provide you with a design spec today (yep, even this needs
> > consideration on contrast, placement, visibility and clutter - for all
> > screens!)"
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/solarisbetter/beta/issues/34#issuecomment-20453396>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/34#issuecomment-20453477
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by dhanur** [comment]
Hey John, attached is the guideline. Basically,
- We move Why Solar? and Why Sunible to accomodate the phone element.
- Spacing outlined in image, element needs to be VCI (vertical-center-aligned) with text on the line.
- I didn't create a graphic because I'd like to use a flat UI element.

This solves a few problems,
- Position works with every page (element in bottom corner clutters the dashboard page)
- Position also draws attention to the questions up top.
- Element also sets up for next week, where all we have to do is embed the Click2Call code snippet to the element.

Please let me know if you have any questions (or call 1800-979-2215!)

-DG

![image](https://f.cloud.github.com/assets/4460231/747330/efb1979c-e457-11e2-82af-b9fe399ba4db.png)

**Comment by rlytvynchuk** [comment]
done. Assigned to QA.

Screenshot
![image](https://f.cloud.github.com/assets/1098812/792534/a3ac33e4-eba4-11e2-8e48-2635ab95e76c.png)

**Comment by svlasenko** [comment]
I verified in Trunk and Master and merged everything to Master. I did sanity testing in Master and everything looks fine in Master right now.
