### ISSUE TITLE
Dashboard - single page scroll

### ISSUE THREAD

**Issue by ghost** [dhanur/Sunible-Beta#39]
Display installers in a single page instead of the panel approach where the installers are scrolled within a window area.  The whole page scrolls like Kayak.

The You Have Selected box floats and remains on the page as the user scrolls the page.  
Vertical top-align "You have Selected" box + button with scroll frame

**Comment by rlytvynchuk** [comment]
issue done. Assigned to QA

For this moment Dashboard has built-in browser scroll. Implementation for Nano scroll support for entire page is more enhancement than part of the bug, 'cause:
- it would affect other pages (header and footer are shared), so we need to enable it for some pages and disable for others.
- it requires more time for implementation that current sprint has.

If it's needed lets add it as additional issue and add to some future sprint

**Comment by svlasenko** [comment]
Verified in Master branch

**Comment by dhanur** [comment]
Roman, built-in browser scroll is EXACTLY what we needed .. so this implementation is perfect. Sorry if the issue was unclear.
