### ISSUE TITLE
Error getting providers list

### ISSUE THREAD

**Issue by svlasenko** [dhanur/Sunible-Beta#42]
Steps to reproduce:
1. Checkout to Master brunch 
2. Open Sunible site
3. Provide zipcode information and click go 

Actual result: Error message apears "Error getting providers list: SyntaxError: JSON.parse: unexpected character"

This issue not reproducible on trunk branch

![image](https://f.cloud.github.com/assets/1586612/750957/3ee40bbc-e4e2-11e2-95a0-c22ea7feeb4b.png)

**Comment by rlytvynchuk** [comment]
I found that in file db_vars.php in revision a56d68a7708dd61daa92b8f52b51f8aca15106c8 database name "torrohol_ca_csi" was changed to 'sunible'

Let's notify each other in case something is changed in environment, so we're synchronized. The changes to DB (name, sql queries and so on) should be applied for everybody.

**Comment by rlytvynchuk** [comment]
assigned to John to decide which db name should be used

**Comment by ghost** [comment]
Roman,

I use db_vars.php so the code runs both on my local machine and
hostmonster.  The db_vars.php file on my local machine contains different
values than the one in the repository and the one in Hostmonster.

The db name in hostmonster is "torrohol_ca_csi" and on my local machine is
"sunible".  The user id and password information is also different on the
two platforms.   The correct db_vars.php uses "torrohol_ca_csi" for the
database and should be used.

I probably pushed the local file up by accident.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by rlytvynchuk** [comment]
It happens =). Let's use the same db name and user. This way we get rid of such situations in future. You can easily rename your database in tool you're using for db management (phpmyadmin or something else)

**Comment by ghost** [comment]
I'll take care of it today.  Thanks.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by dhanur** [comment]
Can we close this?

**Comment by svlasenko** [comment]
Verified in Master brunch
