### ISSUE TITLE
New graphic on Landing Page

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#49]
Design specs here: http://cl.ly/3k0G2E3e2a0l

PNG Icons here: http://cl.ly/1R2O3D0E3R0Z

**Comment by rlytvynchuk** [comment]
new design delivered. Assigned to QA

**Comment by dhanur** [comment]
Hi Roman, I do not have Tower installed yet .. could you please push this to dev.sunible.com or anywhere else so I can can review? Thanks.

**Comment by rlytvynchuk** [comment]
I do not have the access to hosting environment. Please ask John to do this.

Here is the screenshot. Click it to view full size

![sunible_homepage](https://f.cloud.github.com/assets/1098812/777991/d226fdb8-e9a5-11e2-8bdc-571e4479bbf7.png)

**Comment by dhanur** [comment]
The (Graphic + Zip Code Box) is not vertical-center-aligned between top and bottom guides as outlined below. Everything else looks ok.

![image](https://f.cloud.github.com/assets/4460231/778081/ab6d01c0-e9a7-11e2-96fe-88baa0d52b98.png)

**Comment by ghost** [comment]
All:

Tanner has SmartGit installed and access to hosting environment.  This
would be a good exercise to practice production pushes for him.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by swenson86** [comment]
Stephen and I are at Intersolar this afternoon. I will look at it when we
get back to our computers.

**Comment by dhanur** [comment]
Tanner, 

Please DON'T push this to production, there is an alignment issue with the graphic.

I will take over all production pushes, once I have a hands on with John. 

Cheers,

Dhanur 
On July 10, 2013 at 2:47:19 PM, Tanner (notifications@github.com) wrote:

Stephen and I are at Intersolar this afternoon. I will look at it when we  
get back to our computers.

**Comment by rlytvynchuk** [comment]
Alignment issue fixed. Please test in trunk

**Comment by rlytvynchuk** [comment]
![homepage_with_guides](https://f.cloud.github.com/assets/1098812/786443/27bf0c84-eab4-11e2-8177-c1bd965d1619.png)

**Comment by dhanur** [comment]
Tested in dev environment and everything looks ok .. but I cannot see the icons, not sure where those images are hosted. Sveta, if everything is ok with you .. please merge with master and we will push to production ASAP.

![image](https://f.cloud.github.com/assets/4460231/791354/ed26a468-eb41-11e2-8a4b-fcdd4913846a.png)

**Comment by svlasenko** [comment]
Yes, I can see icons. I updated a Trunk brunch and I think the icons should be smaller. I have resolution 1280x800 on my laptop and I can't do more.
![image](https://f.cloud.github.com/assets/1586612/792296/6b0e23fa-eb84-11e2-9f81-a7e7bacff181.png)

**Comment by rlytvynchuk** [comment]
Images were delivered in my first commit. Both me and Svetlana see them in trunk.

Icons size is a question to Dhanur, not developer. Item assigned to him. If current icon size is ok, return to Svetlana, so she merges new design to master

**Comment by dhanur** [comment]
Current icon size is ok, please merge to master.
