### ISSUE TITLE
Remove ugly line that appears next to FAQ scrollbar

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#5]
This one .. 
![image](https://f.cloud.github.com/assets/4460231/520751/6bfd8db4-bf47-11e2-8930-9ffcc9ad4da3.png)

**Comment by dhanur** [comment]
Hi John, this still appears on all browsers I have tested on (using a Mac)

**Comment by ghost** [comment]
I don't see it in Windows.  Will need to make modifications at work and view results on Mac to ensure it;s gone

**Comment by ghost** [comment]
Dhanur - since yours is the only computer that this occurs on, I am going to close out this bug.  If you find out the setting that creates it effect on your computer, please let me know.  Also, if it occurs on another computer I will re-open and investigate.

**Comment by dhanur** [comment]
Ok
Thanks,

Dhanur
