### ISSUE TITLE
Change text on Dashboard button

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#52]
From "Lets Get Sunible" to "Request Quotes"

**Comment by rlytvynchuk** [comment]
changes delivered to Master. Assigned to John to publich on Hostmonster

**Comment by svlasenko** [comment]
Hi John,

I verified this button in Master and Trunk everything looks fine.

**Comment by ghost** [comment]
The button text is correct in master and trunk.  However, the text is incorrect in production.  

Fix:  Pull down master and push to production.  This will over-write the incorrect button text.
