### ISSUE TITLE
Remove word "yet" in first sentence of sign up overlay text - Resubmitting because not fixed

### ISSUE THREAD

**Issue by suniblestephen** [dhanur/Sunible-Beta#54]

**Comment by ghost** [comment]
Change made and pushed to Trunk for QA.

**Comment by suniblestephen** [comment]
Thanks! That has been bugging me.

ST

**Comment by svlasenko** [comment]
I verified this in Trunk and sentence not contains word "yet".

**Comment by ghost** [comment]
Sveta,

I pulled down the latest version of Trunk and the change is there.  Can you check again and contact me directly if you can’t see it?

John

**Comment by svlasenko** [comment]
Hi John,

I checked one more time in Trunk and I can't see word "yet".

Svetlana
