### ISSUE TITLE
"Go" button is blue color on Main page

### ISSUE THREAD

**Issue by svlasenko** [dhanur/Sunible-Beta#55]
"Go" button has a blue color and looks smaller then area for zip-code. 
Please, see at the attached file.

![image](https://f.cloud.github.com/assets/1586612/792299/5eaa8b2a-eb85-11e2-87de-2f0206967a55.png)

**Comment by suniblestephen** [comment]
Button should be red

**Comment by svlasenko** [comment]
Actually, all red buttons became blue color in Trunk.

**Comment by suniblestephen** [comment]
woops, they need to be red, how/who makes this change?

-ST

On Sat, Jul 13, 2013 at 12:05 AM, svlasenko notifications@github.comwrote:

> Actually, all red buttons became blue color in Trunk.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/solarisbetter/beta/issues/55#issuecomment-20915870
> .

## 

_Stephen D. Torres_
Founder & CEO

```
         Solar Simplified
```

55 Harrison Street, 3rd Floor
Oakland, CA 94607

Office:   (800) 979-2215 Ext.101
Mobile:  (925) 518-9133
Skype:  stephen.d.torres
LinkedIn:  stephendtorres http://www.linkedin.com/in/stephendtorres
stephen@sunible.com

**Comment by rlytvynchuk** [comment]
It's in John's commit 394619c4fb08b64e0563a268d6dabaff6dec6f6a

He accidentaly removed forms.css thinking it's duplicate of fonts.css. I restored and delivered to trunk

**Comment by rlytvynchuk** [comment]
moved to QA

**Comment by ghost** [comment]
Yes, blame is mine.  I read it as a duplicate of fonts.css and removed the reference to forms.css in my last commit.

My apologies.  Yet another reason to use GitHub....

**Comment by svlasenko** [comment]
Verified in Trunk branch
