### ISSUE TITLE
Wrong text on Sign-up box.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#8]
Roman got the text wrong for both the sign-up boxes (non-Fresno Zip and non-CA zip)

Should be as below, including line breaks.

"We are not yet in your city right, but we won’t stop working until we are.
No really, we won’t stop working until we make every city Sunible!
Sign up and be the first to know when we launch..."

**Comment by ghost** [comment]
It's easy enough to change the text but I see why Roman did it this way.  If the one line of text is replaced with three , it will force the bottom links off the page requiring a vertical scroll bar.  We could try moving the title and map up  higher on the page to make room at the bottom, but that may be a lot of work.  How important is it to have 3 lines?

**Comment by dhanur** [comment]
Not sure what you're referring to. The text on the sign-up modal box has 3 lines now. He just got the line breaks and the text wrong.

**Comment by ghost** [comment]
Had the wrong page. (see attached)  I see the one  you are referring to now.  Will fix tonight. 
![sign up](https://f.cloud.github.com/assets/3856727/524388/7b861e5a-c112-11e2-98da-cec727a34328.jpg)
