### ISSUE TITLE
Unequal padding on Sign-Up boxes.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#9]
Just like we equalized Padding on the FAQs box, could we do the same on both the Sign-up boxes? We could either refine padding or resize box to achieve the desired result. See below.

Current: 
![image](https://f.cloud.github.com/assets/4460231/545155/15093262-c25b-11e2-8a80-93030cb31a9d.png)

Requested: 
![image](https://f.cloud.github.com/assets/4460231/545153/fec557e2-c25a-11e2-9a85-90ffb1e8ae8c.png)

**Comment by ghost** [comment]
centered horizontally.  too hard to get it exact vertically because of the way the box is sized.
